version: '3.8'

services:
  reverse-proxy-gui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-8000}:${WEB_PORT:-8000}"
      - "${PROXY_PORT:-8080}:${PROXY_PORT:-8080}"
    environment:
      - WEB_PORT=${WEB_PORT:-8000}
      - PROXY_PORT=${PROXY_PORT:-8080}
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - proxy-data:/app/data
    restart: unless-stopped

volumes:
  proxy-data: