// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReverseProxy.Data;

#nullable disable

namespace ReverseProxy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250415222416_RemoveIsEnabledProperty")]
    partial class RemoveIsEnabledProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ReverseProxy.Models.Mapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveDestination")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveDestination = 1,
                            Destination1 = "https://api1.example.com",
                            Destination2 = "https://api2.example.com",
                            Name = "Default Route",
                            RoutePattern = "/api/{**catch-all}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
